# Generated by Django 3.2.4 on 2021-06-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_auto_20210620_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
