# Generated by Django 3.2.4 on 2021-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0003_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
    ]
