# Generated by Django 3.2.4 on 2021-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relationships', '0005_auto_20210622_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'All Country'},
        ),
    ]
