# Generated by Django 3.2.4 on 2021-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondblog', '0003_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
