# Generated by Django 3.2.4 on 2021-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondblog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
